name: Daily Bonus Script

on:
  schedule:
    - cron: '0 6 * * *'  # каждый день в 6:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Firefox and dependencies
        run: |
          sudo apt update
          sudo apt install -y firefox xvfb wget unzip
          wget https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.34.0-linux64.tar.gz
          tar -xzf geckodriver-v0.34.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Install Python packages
        run: |
          pip install selenium webdriver-manager requests

      - name: Run the script
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          xvfb-run python main.py
